# Generated by Django 3.2.4 on 2021-08-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210811_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.IntegerField(
                choices=[(1, 'ข่าวประกาศ'), (2, 'โฆษณา'), (3, 'บันทึก')], default=1),
            preserve_default=False,
        ),
    ]
